### PR TITLE
emits "tokenExpired" when encountering "expired access/refresh token"

### PR DESCRIPTION
**Pull request by joeferraro**

### CODE REVIEW

**Comment by kidtsunami** [comment]
@joeferraro this should be live in npm v0.1.11 (I remembered to build it this time...)

**Comment by kidtsunami** [comment]
fetch-salesforce@0.1.11

**Comment by joeferraro** [comment]
bitmoji

**Comment by kidtsunami** [comment]
bitmoji

**Comment by joeferraro** [comment]
@kidtsunami unfortunately, it doesn't look like the compiled version found its way to npm ... can you confirm?

**Comment by joeferraro** [comment]
hm, maybe it's because there's a difference between package.json version and npm version?

**Comment by joeferraro** [comment]
ah there it is in `yarn upgrade fetch-salesforce@0.1.11`. We just need to bump the package version in github.

**Comment by kidtsunami** [comment]
I really need a script that wraps npm publish in something that:
a) runs the typescript build of the package
b) updates the package.json version
c) publishes the package
d) commits and pushes the commit up to github

**Pull request merged**
